"""Fix Agent node -- for LOCATOR_CHANGE / WAIT_SYNC classifications, drafts a
minimal test-code fix grounded in KB_FUNCTIONAL_DOCS and opens a draft PR."""

from __future__ import annotations

import logging
import uuid

from app.cost.optimizer import enforce_json_only
from app.graph.state import ClusterState
from app.integrations.github_tool import get_github_adapter
from app.llm import LLMRouter
from app.memory.knowledge_bases import KB_FUNCTIONAL_DOCS, get_kb_store
from app.models import FixResult
from app.prompts.library import FIX_SYNTHESIS_SYSTEM_PROMPT, fix_user_prompt

logger = logging.getLogger("qa_agent.graph.fix")

_llm = LLMRouter()


def fix_node(state: ClusterState) -> dict:
    cluster = state["cluster"]
    tracker = state["cost_tracker"]

    kb = get_kb_store()
    doc_hits = kb.query(KB_FUNCTIONAL_DOCS, cluster.representative.error_message, top_k=2)
    doc_context = [h["text"] for h in doc_hits]

    payload, llm_resp = _llm.complete_json(
        tier="deep",
        system_prompt=FIX_SYNTHESIS_SYSTEM_PROMPT + "\n" + enforce_json_only('{"file_path": str, "diff_summary": str, "confidence": float}'),
        user_prompt=fix_user_prompt(cluster, doc_context),
    )
    tracker.record("deep", llm_resp)

    file_path = payload.get("file_path") or f"src/test/specs/{cluster.representative.test_name}.spec.ts"
    diff_summary = payload.get("diff_summary", "")
    confidence = float(payload.get("confidence", 0.5))

    github = get_github_adapter()
    branch_name = f"agentic-qa/fix-{cluster.signature[:8]}-{uuid.uuid4().hex[:8]}"
    pr = github.open_pull_request(
        branch_name=branch_name,
        file_path=file_path,
        file_content=f"// Auto-generated by the Agentic QA system\n// {diff_summary}\n",
        commit_message=f"fix(qa-agent): {diff_summary[:72]}",
        pr_title=f"[QA-Agent] Fix locator/wait issue in {cluster.representative.test_name}",
        pr_body=f"Auto-generated fix for cluster `{cluster.signature[:8]}` "
        f"({cluster.size} affected test run(s)).\n\n{diff_summary}",
    )

    fix_result = FixResult(
        applied=True,
        file_path=file_path,
        diff_summary=diff_summary,
        pr_url=pr.get("pr_url"),
        verified=confidence >= 0.7,
        verification_notes="Confidence-gated auto-verification; human review still required before merge."
        if confidence >= 0.7
        else "Low-confidence fix -- flagged for mandatory human review.",
        simulated=pr.get("simulated", True),
    )
    logger.info("[fix] cluster=%s pr=%s simulated=%s", cluster.signature[:8], fix_result.pr_url, fix_result.simulated)
    return {"fix_result": fix_result}
